site_name: Wave
theme:
    name: material
    logo: assets/images/logo_colored_64px.png
    favicon: assets/images/logo_colored.png
    font:
        text: Nunito Sans
        code: JetBrains Mono
    features:
        - navigation.tabs
        - navigation.expand
extra_css:
    - assets/styles/style.css
repo_url: https://github.com/BradSharp/Wave
repo_name: BradSharp/Wave
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.superfences