site_name: Wave
repo_url: https://github.com/BradSharp/Wave
repo_name: BradSharp/Wave
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.superfences
theme:
    name: material
    logo: assets/images/logo_colored_64px.png
    favicon: assets/images/logo_colored.png
    font:
        text: Nunito Sans
        code: JetBrains Mono
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tracking
        - navigation.top
extra_css:
    - assets/stylesheets/style.css
extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/bradsharppp
copyright: Copyright &copy; 2021 - 2021 Brad Sharp
nav:
    - Home: index.md
    - Getting Started:
        - Introduction: guide/index.md
        - Components: guide/components.md
        - States: guide/states.md
    - API Reference:
        - api/index.md
        - State: api/state.md
        - Symbols: api/symbols.md
        - Types:
            - App: api/app.md
            - Object: api/object.md
