name: release
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: Release Tag
        required: true
        default:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Tarball
        run: |
          cd ${{ github.workspace }}
          tar -cf release.tar Wave
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.releaseTag }}
          body: |
            Latest release of ${{ github.repository }}
          artifacts: "${{ github.workspace }}/release.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
