name: release
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .build
      - run: tar -cf .build/release.tar ${{ github.workspace }}
      - uses: ncipollo/release-action@v1
        with:
          tag: test
          body: |
            Latest release of ${{ github.repository }}
          artifacts: ".build/release.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
