name: ci 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tar -cf release.tar ${{ github.workspace }}/Wave
      - run: ls ${{ github.workspace }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GITHUB_SHA }}
          body: |
            Latest release of ${{ env.GITHUB_REPOSITORY }}
          artifacts: "release.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
