name: release
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        cd ${{ github.workspace }}
        tar -cf release.tar Wave
      - uses: ncipollo/release-action@v1
        with:
          tag: test4
          body: |
            Latest release of ${{ github.repository }}
          artifacts: "${{ github.workspace }}/release.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
