name: release
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tar -cf .build/release.tar /Wave
      - uses: ncipollo/release-action@v1
        with:
          tag: ${GITHUB_SHA::8}
          body: |
            Latest release of ${{ github.repository }}
          artifacts: ".build/release.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
